name: 'PR Summarizer with Jokes'
description: 'Automatically summarizes pull requests and adds a joke for fun'
author: 'Noel Bansikah'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Determine Version
      id: get_version
      shell: bash
      run: |
        # Extract version from the 'uses' directive context
        VERSION=$(echo "${{ github.action_ref }}" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' || echo "latest")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Download Precompiled Binary
      shell: bash
      run: |
        VERSION="${{ steps.get_version.outputs.version }}"
        curl -L -o pr-summarizer.tar.gz \
          "https://github.com/bansikah22/pr-summarizer/releases/download/$VERSION/pr-summarizer-$VERSION.tar.gz"
        ls -lh pr-summarizer.tar.gz
        file pr-summarizer.tar.gz
        tar -xzf pr-summarizer.tar.gz
        chmod +x pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Run PR Summarizer
      shell: bash
      run: ./pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}