name: 'PR Summarizer with Jokes'
description: 'Automatically summarizes pull requests and adds a joke for fun'
author: 'Noel Bansikah'
branding:
  icon: 'message-square'
  color: 'purple'
inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Precompiled Binary
      shell: bash
      run: |
        # Get the action version from the reference
        ACTION_VERSION="${{ github.action_ref }}"
        
        # Remove 'v' prefix if present
        VERSION="${ACTION_VERSION#v}"
        
        # As fallback, you can hardcode the latest version
        if [[ -z "$VERSION" ]]; then
          VERSION="1.0.0"
          echo "No version detected, using default: $VERSION"
        else 
          echo "Using version: $VERSION"
        fi
        
        echo "Downloading from: https://github.com/bansikah22/pr-summarizer/releases/download/v${VERSION}/pr-summarizer-v${VERSION}.tar.gz"
        
        # Download with better error handling
        if ! curl -L -f -o pr-summarizer.tar.gz \
          "https://github.com/bansikah22/pr-summarizer/releases/download/v${VERSION}/pr-summarizer-v${VERSION}.tar.gz"; then
          echo "Download failed! Check if release exists at: https://github.com/bansikah22/pr-summarizer/releases/tag/v${VERSION}"
          exit 1
        fi
        
        # Debug info
        ls -la pr-summarizer.tar.gz
        file pr-summarizer.tar.gz
        
        # Extract with error handling
        if ! tar -xzf pr-summarizer.tar.gz; then
          echo "Failed to extract archive. It may be corrupted or not a valid gzip file."
          exit 1
        fi
        
        chmod +x pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
    - name: Run PR Summarizer
      shell: bash
      run: ./pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}