name: 'PR Summarizer with Jokes'
description: 'Automatically summarizes pull requests and adds a joke for fun'
author: 'Noel Bansikah'
branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  github_token:
    description: 'GitHub token for API access'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Download Precompiled Binary
      shell: bash
      run: |
        # Use the specific version for now (v1.0.2)
        curl -L -o pr-summarizer.tar.gz \
          "https://github.com/bansikah22/pr-summarizer/releases/download/v1.0.2/pr-summarizer-v1.0.2.tar.gz"
        # Debug: Show file size and type
        ls -lh pr-summarizer.tar.gz
        file pr-summarizer.tar.gz
        # Extract
        tar -xzf pr-summarizer.tar.gz
        chmod +x pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Run PR Summarizer
      shell: bash
      run: ./pr-summarizer
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}