name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Package Binary
        run: |
          tar -czf pr-summarizer-${{ github.ref_name }}.tar.gz -C target/release pr-summarizer
        if: success()

      - name: Debug Release Info
        run: |
          echo "Tag: ${{ github.ref_name }}"
          echo "Binary: pr-summarizer-${{ github.ref_name }}.tar.gz"
        if: success()

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's New
            - Automated PR summarization with jokes 🎉
            - Enhanced with emojis for a polished look ✨
            - Built with Rust 🦀
            - See [README.md](README.md) for usage instructions

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: pr-summarizer-${{ github.ref_name }}.tar.gz
          asset_name: pr-summarizer-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip