name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Package Binary
        run: |
          # Create a temporary directory for packaging
          mkdir -p package
          cp target/release/pr-summarizer package/
          
          # Package the binary properly
          cd package
          tar -czf ../pr-summarizer-${{ github.ref_name }}.tar.gz pr-summarizer
          cd ..
          
          # Verify the archive
          echo "Verifying archive contents:"
          tar -tvf pr-summarizer-${{ github.ref_name }}.tar.gz
        if: success()

      - name: Create and Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## What's New
            - Automated PR summarization with jokes 🎉
            - Enhanced with emojis for a polished look ✨
            - Built with Rust 🦀
            - See [README.md](README.md) for usage instructions
          files: pr-summarizer-${{ github.ref_name }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}